ckpt = [
  "/fs/ess/PAS2136/samuelstevens/checkpoints/saev/g49kbj2j/sae.pt",
  "/fs/ess/PAS2136/samuelstevens/checkpoints/saev/vde7lady/sae.pt",
]

dump_to = "/fs/scratch/PAS2136/samuelstevens/saev/acts/butterflies"

[data]
shard_root = "/fs/scratch/PAS2136/samuelstevens/cache/saev/94aef9fc4ded2ce6d62ca904a721a6ef7ca6419054b34da6c349b97d7e7d2723"
layer = 13
batch_size = 8_192

[images]
root = "/fs/scratch/PAS2136/samuelstevens/datasets/butterflies"
