# Unified sweep configuration for baseline methods evaluation on CUB-200
# 
# Methods to evaluate
method = ["linear-clf"]

# Number of prototypes/components for each method
n_prototypes = [128, 512, 2048, 8224, 32768]

# Number of training samples for trait selection
n_train = [16, 64, 256, 1024, 4096, -1]  

# Random seeds for reproducibility
seed = [17, 42, 137]

layer = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
