vit_ckpt = "/fs/ess/PAS2136/samuelstevens/models/dinov3/dinov3_vitl16_pretrain_lvd1689m-8aa4cbdd.pth"
d_vit = 1024

slurm_acct = "PAS2136"
slurm_partition = "nextgen"
n_hours = 4.0

# Random seeds for statistical significance
seed = [17, 42, 1337]

[imgs]
root = "/fs/scratch/PAS2136/samuelstevens/datasets/fish-vista-segfolder"
img_label_fname = "image_labels.txt"
