tag = "train-v2.0"

lr = [3e-4, 1e-3, 3e-3]

n_lr_warmup = 500

[sae]
normalize_w_dec = true
remove_parallel_grads = true
exp_factor = [16]
activation = "batch-top-k"
activation.top_k = [32, 128, 512, 2048]

[data]
layer = [13, 17, 21, 23]
