lr = [3e-4, 1e-3, 3e-3]

n_lr_warmup = 500
n_sparsity_warmup = 6000

runs_root = "/fs/ess/PAS2136/samuelstevens/saev/runs"

[sae]
normalize_w_dec = true
remove_parallel_grads = true
exp_factor = [16]

[objective]
sparsity_coeff = [4e-4, 8e-4, 1.6e-3]

[data]
layer = [13, 15, 17, 19, 21, 23]
