site_name: saev
docs_dir: src
site_dir: api
site_url: https://osu-nlp-group.github.io/saev/api

theme:
  name: material
  palette:
    primary: custom
  font: false
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
    - content.action.edit

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OSU-NLP-Group/saev

nav:
  - Home: index.md
  - Users:
      - Guide: users/guide.md
      - Inference: users/inference.md
  - Developers:
      - Contributing: developers/contributing.md
      - Shard Protocol: developers/protocol.md
      - Disk Layout: developers/disk-layout.md
  - API: api/
  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            merge_init_into_class: true
            show_root_heading: false
  - gen-files:
        scripts:
          - ../scripts/docs.py
  - literate-nav:
      nav_file: summary.md

markdown_extensions:
  - admonition
  - footnotes
